### ISSUE TITLE
Pass through SAN string to visitor

### ISSUE THREAD

**Issue by parszab** [niklasf/rust-pgn-reader#34]
Would it be possible, to pass the actual SAN String as well to  `Visitor.san`? I'm working on a chess database, and would like to rebuild the proper PGN String (in well formed export format) as well during the parsing. To get the SAN string back a call to a Shakmaty board would be necessary for extra cost (didn't even find it yet tbh).

**Comment by niklasf** [comment]
Hi. I don't think its a good idea, because the parser leniently accepts some syntactical quirks and over-specified notation, while most consumers would expect canonical SAN.

For your concrete use case, to create well-formed PGN in export format, correct disambiguation is required. So there's no way around actually keeping track of the position and disambiguating moves accordingly.

**Comment by parszab** [comment]
> For your concrete use case, to create well-formed PGN in export format, correct disambiguation is required. So there's no way around actually keeping track of the position and disambiguating moves accordingly.

Fair enough, thanks for your reply! For this, it would be great if I could use Shakmaty: what are your plans to bring it to the level of python-chess? (E.g. I don't think Board/Position has a method to return SAN string for a move yet.) Any time-frame in mind? And/or are you accepting PRs with such features?

**Comment by niklasf** [comment]
shakmaty already supports this. See https://docs.rs/shakmaty/latest/shakmaty/san/index.html for examples.

**Comment by parszab** [comment]
> shakmaty already supports this. See https://docs.rs/shakmaty/latest/shakmaty/san/index.html for examples.

Fantastic, thanks!
